mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
ipv6: false

dns:
  enable: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  nameserver:
    - 1.1.1.1
    - 8.8.8.8

proxies:
  - name: "ZIVPN-CORE-NATIVE"
    type: socks5
    server: 127.0.0.1
    port: 7777

proxy-groups:
  - name: "ZIVPN-SYSTEM"
    type: select
    proxies:
      - "ZIVPN-CORE-NATIVE"

rules:
  - MATCH,ZIVPN-SYSTEM