# HYSTERIA_CONFIG: {"ip":"id3vvip.ipservers.xyz","pass":"0nC0meoss","obfs":"hu``hqb`c","port_range":"6000-7750,7751-9500,9501-11250,11251-13000,13001-14750,14751-16500,16501-18250,18251-19999","mtu":"9000","auto_boot":false,"recv_window_multiplier":1.0}
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: rule
log-level: debug
external-controller: 127.0.0.1:9090

proxies:
  - name: "ZIVPN-Core"
    type: socks5
    server: 127.0.0.1
    port: 7777
    udp: false

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "ZIVPN-Core"
  - name: "Keep-Alive"
    type: url-test
    proxies:
      - "ZIVPN-Core"
    url: 'http://www.gstatic.com/generate_204'
    interval: 20
    tolerance: 500


rules:
  - IP-CIDR, 127.0.0.0/8, DIRECT, no-resolve
  - IP-CIDR, ::1/128, DIRECT, no-resolve
  - MATCH,PROXY

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*'
    - '+.lan'
    - '+.local'
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
  nameserver:
    - https://1.1.1.1/dns-query
    - https://8.8.8.8/dns-query
  fallback:
    - https://1.0.0.1/dns-query
    - https://8.8.4.4/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4

